version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dfp
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=dfp
    ports:
      - "9000:9000"
    volumes:
      - ".:/app"
    command: "gunicorn --bind 0.0.0.0:9000 api.budgetsdata:application"
    links:
      - postgres

  graphql-engine:
    image: hasura/graphql-engine:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:1234@postgres:5432/dfp
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"